version: v1
description: Workflow to echo a nice hello world message to the logs

parameters:
  stack_name:
    description: CloudFormation stack name for wordpress db
    default: wordpressdb
  database_name:
    description: name for wordpress db
    default: wordpress
  database_user:
    description: user name for wordpress db
    default: wordpress
  database_password:
    description: password for wordpress db
    default: w0rdpre55

steps:
  - name: deploy-wordpress-db
    # image: timidri/cloudformation-deployer:latest
    image: projectnebula/cloudformation-deployer:latest
    spec:
      aws:
        accessKeyID:
          $type: Secret
          name: key-id
        secretAccessKey:
          $type: Secret
          name: access-key
        region: eu-west-2
      stackName:
        $type: Parameter
        name: stack_name
      templateFile: wordpress/cf.yaml
      parameters:
        DBName:
          $type: Parameter
          name: database_name
        DBUser:
          $type: Parameter
          name: database_user
        DBPassword:
          $type: Parameter
          name: database_password
      git:
        name: nebula-workflows
        repository: https://github.com/timidri/nebula-workflows.git

  - name: deploy-wordpress-app
    image: projectnebula/helm-deployer:latest
    dependsOn:
      - deploy-wordpress-db
    spec:
      name: wordpress
      values:
        wordpressBlogName: wordpress
        mariadb:
          enabled: false
        externalDatabase:
          database:
            $type: Parameter
            name: database_name
          user:
            $type: Parameter
            name: database_user
          password:
            $type: Parameter
            name: database_password
          host:
            $type: Output
            name: DBHost
            taskName: deploy-wordpress-db
          port:
            $type: Output
            name: DBPort
            taskName: deploy-wordpress-db
        wordpressSkipInstall: true
      chart: stable/wordpress
      namespace: wordpress
      recreatePods: true
      cluster:
        name: gke_pipelines-for-containers_europe-west1-b_puppet-pipelines
        url:
          $type: Secret
          name: kube-url
        cadata:
          $type: Secret
          name: kube-cadata
        token:
          $type: Secret
          name: kube-token

  - name: show wordpress IP
    image: projectnebula/kubectl:latest
    dependsOn:
      - deploy-wordpress-app
    spec:
      command: get
      args:
        - "svc"
      namespace: wordpress
      cluster:
        name: mgke_pipelines-for-containers_europe-west1-b_puppet-pipelines
        url:
          $type: Secret
          name: kube-url
        cadata:
          $type: Secret
          name: kube-cadata
        token:
          $type: Secret
          name: kube-token
