version: v1
description: Workflow to echo a nice hello world message to the logs

parameters:
  stack_name:
    description: CloudFormation stack name for wordpress db
    default: wordpressdb

steps:
  - name: slack-notification
    image: projectnebula/slack-notification:latest
    spec:
      apitoken:
        $type: Secret
        name: slack-token
      channel: "#nebula-workflows"
      message: "Testing slack notifications by DbT."
      username: me
  - name: deploy-wordpress-db
    image: timidri/cloudformation-deployer:latest
    spec:
      aws:
        accessKeyID:
          $type: Secret
          name: key-id
        secretAccessKey:
          $type: Secret
          name: access-key
        region: eu-west-2
      stackName:
        $type: Parameter
        name: stack_name
      templateFile: wordpress/cf.yaml
      git:
        name: nebula-workflows
        repository: https://github.com/timidri/nebula-workflows.git
